# Generated by Django 3.2.6 on 2021-09-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('to_do', 'ToDo'), ('ready', 'Ready'), ('in_pr', 'In Progress'), ('complt', 'Completed')], default='to_do', max_length=10)),
                ('priority', models.CharField(choices=[('0_low', 'Low'), ('1_med', 'Medium'), ('2_high', 'High'), ('3_block', 'Blocking')], default='1_med', max_length=10)),
            ],
        ),
    ]
