# Generated by Django 3.2.6 on 2021-09-28 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('state', models.TextField(choices=[('to_do', 'ToDo'), ('ready', 'Ready'), ('in_pr', 'InProgress'), ('complt', 'Completed')], default='to_do')),
                ('priority', models.TextField(choices=[('0_low', 'Low'), ('1_med', 'Medium'), ('2_high', 'High'), ('3_block', 'Blocking')], default='1_med')),
            ],
        ),
    ]
