# Generated by Django 3.2.6 on 2021-09-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskTracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktrack',
            name='state',
            field=models.CharField(choices=[('to_do', 'ToDo'), ('ready', 'Ready'), ('in_pr', 'InProgress'), ('complt', 'Completed')], default='to_do', max_length=10),
        ),
    ]
