# Generated by Django 3.2.6 on 2021-09-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskTracks', '0002_alter_tasktrack_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktrack',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tasktrack',
            name='priority',
            field=models.TextField(choices=[('0_low', 'Low'), ('1_med', 'Medium'), ('2_high', 'High'), ('3_block', 'Blocking')], default='1_med'),
        ),
        migrations.AlterField(
            model_name='tasktrack',
            name='state',
            field=models.TextField(choices=[('to_do', 'ToDo'), ('ready', 'Ready'), ('in_pr', 'InProgress'), ('complt', 'Completed')], default='to_do'),
        ),
    ]
