# Generated by Django 3.2.6 on 2021-08-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskTracks', '0003_auto_20210812_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktrack',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='date'),
        ),
    ]
