# Generated by Django 3.2.6 on 2021-09-27 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taskTracks', '0003_auto_20210927_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktrack',
            name='date',
            field=models.DateTimeField(editable=False, verbose_name=django.utils.timezone.now),
        ),
    ]
