# Generated by Django 3.2.6 on 2021-08-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskTracks', '0004_alter_tasktrack_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktrack',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
