# Generated by Django 3.2.6 on 2021-08-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskTracks', '0006_alter_tasktrack_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktrack',
            name='priority',
            field=models.CharField(choices=[('0_low', 'Low'), ('1_med', 'Medium'), ('2_high', 'High'), ('3_block', 'Blocking')], default='1_med', max_length=10),
        ),
    ]
