# Generated by Django 3.2.6 on 2021-08-25 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskTracks', '0008_alter_tasktrack_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktrack',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 25, 17, 51, 34, 763959), null=True),
        ),
    ]
