# Generated by Django 3.2.6 on 2021-08-27 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskTracks', '0011_alter_tasktrack_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktrack',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 27, 10, 26, 2, 841662)),
        ),
    ]
