# Generated by Django 3.2.6 on 2021-08-27 11:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('taskTracks', '0014_alter_tasktrack_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktrack',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 27, 11, 42, 10, 219309, tzinfo=utc)),
        ),
    ]
