# Generated by Django 3.2.6 on 2021-08-27 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taskTracks', '0015_alter_tasktrack_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktrack',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
