# Generated by Django 3.2.6 on 2021-09-06 10:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('taskTracks', '0016_alter_tasktrack_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktrack',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 6, 10, 51, 49, 818095, tzinfo=utc)),
        ),
    ]
